# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../my_flutter'
    
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NK_Native_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  install_all_flutter_pods(flutter_application_path)
  # Pods for NK_Native_ios

  target 'NK_Native_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NK_Native_iosUITests' do
    # Pods for testing
  end

end
